<a href="https://colab.research.google.com/github/RafaelBNN/datasets/blob/main/sampling_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importando as bibliotecas

In [1]:
import io
import pandas as pd
from matplotlib import pyplot as plt
import csv
from google.colab import files

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Importando .csv

In [3]:
%%time
#path = "/content/drive/MyDrive/data/csv_name.csv"
path = "/content/drive/MyDrive/data/openpowerlifting.csv"
df = pd.read_csv(path)

<string>:2: DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.

CPU times: user 5.27 s, sys: 957 ms, total: 6.23 s
Wall time: 8.36 s

In [4]:
df.head()

              Name Sex Event  ... MeetCountry  MeetState       MeetName
0     Abbie Murphy   F   SBD  ...   Australia        VIC  Melbourne Cup
1      Abbie Tuong   F   SBD  ...   Australia        VIC  Melbourne Cup
2   Ainslee Hooper   F     B  ...   Australia        VIC  Melbourne Cup
3  Amy Moldenhauer   F   SBD  ...   Australia        VIC  Melbourne Cup
4     Andrea Rowan   F   SBD  ...   Australia        VIC  Melbourne Cup

[5 rows x 37 columns]

### Sampling

In [ ]:
df2 = df.sample(n=10000)

In [ ]:
df2.head()

                   Name  ...                                           MeetName
164481       Jason Wahl  ...  Brute Strength Gym Shamrock Powerlifting and B...
583869   Roald Kollåsen  ...                                        Kretsstevne
283182    Kemar Randall  ...                         Mansfield Legacy Quad Meet
1022023    María Izetta  ...                Torneo Nacional de Banco y Despegue
483309          C Toves  ...                         9th Annual Whitney Wildcat

[5 rows x 37 columns]

### Exportando .csv modificado

In [ ]:
df2.to_csv('powerlifting2.csv')
files.download('powerlifting2.csv')